### ISSUE TITLE
Use Course Groups function not working

### ISSUE THREAD

**Issue by davefoord** [danmarsden/moodle-mod_dialogue#100]
I don't think that the 'Use Course Groups' function is working. I have enabled this option, yet students can still see students from groups that they are not in, and can send a message to them.

I am sure I have had this working in the past, but have just tested this on 3 different Moodles, and all have behaved the same way.

**Comment by cdipe** [comment]
@davefoord could this issue be connected to the the problem I reported, [https://github.com/danmarsden/moodle-mod_dialogue/issues/91]

**Comment by davefoord** [comment]
@cdipe this may be connected in some way (but I don't understand the technical side of things, so not sure). In my cases, the students are not seeing the other conversations, they are only seeing their own messages - they are however seeing other peoples names appearing in the dropdown list, and are able to start a conversation with these other people.

**Comment by cdipe** [comment]
@davefoord ok, that sounds like a different issue

**Comment by danmarsden** [comment]
yeah - that does sound like a regression with the new user selector - probably a little bit of reworking required there to pass the current users group and the group settings to the custom search web service. I took a look at the moodle core enrol search users function and it doesn't seem to support groups either.

Pull requests welcome, otherwise I'll try to find some time for this in the new year.

**Comment by lengyelke** [comment]
there is a 'usecoursegroups' var in the code, but it is not checked at any stage in the new version, a lot of code was deleted from 3.9
it checks the group setting here:
locallib.php line 56 (ver 3.9) and there is no equivalent in v3.11
we really would like to use that functionality to control who the student can message to

might be useful:

- core_group_get_course_user_groups : Returns all groups in specified course for the specified user.
- core_group_get_group_members : Returns group members.
- core_group_get_activity_allowed_groups : Gets a list of groups that the user is allowed to access within the specified activity.

Thanks
Frank

**Comment by danmarsden** [comment]
thansk @lengyelke - pull requests are welcome! - I'll try to find time for this at some point but I'm sure you can understand I have a lot of demands on any free time I have and all my work on dialogue has been voluntary (unpaid). We needed to replace a lot of the old YUI code and make it follow moodle's coding guidelines better, but it should be easy to add some of these functions back in now that the code conforms better to the standard guidelines.
