### ISSUE TITLE
Description appearing twice in Moodle 4.1

### ISSUE THREAD

**Issue by davefoord** [danmarsden/moodle-mod_dialogue#116]
I notice that in Moodle 4.1.1 the dialogue activity is showing the description twice - once in the 'activity-header' and then again in the 'intro' area.

I have checked this on a couple of Moodles and Dialogue version 4.2

I assume this is a bug...

**Comment by danmarsden** [comment]
Thanks Dave - yeah the Moodle 4.1 rendererers show the description in the header by default to make it more uniform across all plugins - will see if someone here can fix this up.

**Comment by rdt1005** [comment]
Hi Dan, 

Just wondering if there is an update on the above bug?

Cheers

**Comment by danmarsden** [comment]
not yet - I do have it in the queue but as it doesn't have a paying client attached to the work it just has to wait until someone has the time and it ends up near the top of our list of many things we'd like to do... (which it will eventually, I just can't guarantee when.)

Pull requests and or funding for development are always welcome! :-)

**Comment by danmarsden** [comment]
fixed in #122
