### ISSUE TITLE
Collapsible buttons and fa icons are not displayed in Moodle 4.2.2

### ISSUE THREAD

**Issue by namiarj** [danmarsden/moodle-mod_dialogue#117]
Collapsible buttons and fa icons are not displayed in Moodle 4.2.2

I have not been able so far to track down what's causing this. The only fa icon that is displayed is fa-trash-o. The buttons and icons are displayed correctly on mobile devices tho.

**Comment by danmarsden** [comment]
you have found the github repository for the "dialogue plugin" which is an extra plugin that people can add to their Moodle sites. the comment you've posted above doesn't seem to have any reference to this plugin - have you reported it in the right place? - if this really relates to the mod_dialogue plugin can you please add a screenshot that shows the issues?

**Comment by namiarj** [comment]
> you have found the github repository for the "dialogue plugin" which is an extra plugin that people can add to their Moodle sites. the comment you've posted above doesn't seem to have any reference to this plugin - have you reported it in the right place? - if this really relates to the mod_dialogue plugin can you please add a screenshot that shows the issues?

I should have clarified. Yes we are using the latest version of mod_dialougue on Moodle 4.2.2 for the communication of our mentors and mentees. I saw another comment on Moodle plugin repository about icons not working on Moodle 4 so I guess it's reproducible. I'll take some screenshots but I have translated most of the strings.

![2023-08-31-031654_752x189_scrot](https://github.com/danmarsden/moodle-mod_dialogue/assets/25607256/515fda98-9bf3-49d8-9923-dca2c0c41774)

![2023-08-31-031449_1239x548_scrot](https://github.com/danmarsden/moodle-mod_dialogue/assets/25607256/845fb608-e411-45eb-8266-990dedd98423)

**Comment by danmarsden** [comment]
What theme are you using, and does this occur for other plugins/other areas in Moodle? - or just dialogue?

**Comment by namiarj** [comment]
> What theme are you using, and does this occur for other plugins/other areas in Moodle? - or just dialogue?

We are using almondb theme. This also happens on boost. It only happens with dialogue. We tested on Chrome 106 and Edge on Windows 10, Firefox and Chrome on Ubuntu and they all had the display problem. For some reason it doesn't happen on iOS safari.

**Comment by danmarsden** [comment]
Thanks for confirming that! - I don't have a lot of free/spare time to work on dialogue at the moment but I'll try to come back to this sometime - if you have internal development capabilities, pull requests are always welcome!!

**Comment by danmarsden** [comment]
thanks to @namiarj a fix for this is now in the 4.0 and 4.1 branches here in github - I'll push out a new moodle.org plugins db with this fix at some point. thanks!
