### ISSUE TITLE
Push new version to moodle.org

### ISSUE THREAD

**Issue by ewout** [danmarsden/moodle-mod_dialogue#128]
I'm not sure what the process is, but I notice that as of today, version `2022112400` is on moodle.org, but version `2023092200` is the current most up to date branch.

It's rather important for me to have the latest version, since it resolves a bug (#116) that, while trivial, impedes the use of this, for us, essential plugin. I'd really rather not hook up our production environment to a git repo, since that surely will give problems later.

**Comment by danmarsden** [comment]
you can also download the zip package from github - you don't need to "hook up git" to use the code from this repo.
click on the green code button and then the "download zip" that appears on the page.
![Screenshot from 2024-03-08 08-53-48](https://github.com/danmarsden/moodle-mod_dialogue/assets/362798/d4cfb2d1-37c2-4695-a12d-1ed10297a5d0)

I don't push out code regularly to the moodle.org plugins db, but for plugins that pass the standard github actions pipelines most of my plugins will push a version automatically when the version number is changed in the version.php file.

Unfortunately the dialogue plugin doesn't currently pass those tests, but that's something on my backlog that I'd like tofix one day. If you have internal development capabilities feel free to submit a pull request to help or reach out privately if you would like to fund improvements to the plugin to meet your needs.

thanks!

**Comment by ewout** [comment]
Ah, ok, I didn't understand there were tests not passing and that's why it didn't get pushed out to moodle.org.

But that makes it even more problematic to put the current code in production, either by hooking up a git repo or downloading code (in any case , the update workflow would be disrupted).

I'll have a look at the tests, but it's very unlikely I'll be able to contribute, I'm afraid. Thanks anyway for the explanation and your work maintaining this plugin!
