### ISSUE TITLE
Performance issue when viewing conversations

### ISSUE THREAD

**Issue by jwalits** [danmarsden/moodle-mod_dialogue#140]
We have a client who uses the dialogue activity quite heavily. We found a slight performance issue if viewing dialogues when logged in as a user who doesn't have the "mod/dialogue:viewany" capability.

Tracing down the code to: https://github.com/danmarsden/moodle-mod_dialogue/blob/MOODLE_401_STABLE/classes/conversations_by_author.php#L84-L89

There is an extra join that gets added in this case, which blows out the query time to around 45-60s as compared to around 4-5s when a user who has the  "mod/dialogue:viewany" capability is viewing the same page.

For reference, the mdl_dialogue_messages table in our case has around 1.8 million rows and mdl_dialogue_participants table at around 1.3 million rows.

After doing some more digging with Explain, it turns out, we can make this query very much quicker by adding an index for dialogueid on the mdl_dialogue_messages table. 
https://github.com/danmarsden/moodle-mod_dialogue/blob/MOODLE_401_STABLE/db/install.xml#L76

I'll prepare a PR for this shortly. But adding an issue first to get some thoughts/conversation on this issue.

**Comment by jwalits** [comment]
Before index:
![2024-12-06_14-48](https://github.com/user-attachments/assets/5a2813e9-fe0e-49af-be54-08db4ee67176)

After index:

![2024-12-06_14-49](https://github.com/user-attachments/assets/68aac763-8afb-4912-b5a1-c54a49567a09)

**Comment by cdipe** [comment]
@jwalits This sounds great, thank you! At the Linnaeus university in Sweden we use Dialogue a lot, it's a great tool but we have reacted on how long it takes to open.

**Comment by danmarsden** [comment]
Adding a new index sounds like an easy option, go and send that through!

**Comment by jwalits** [comment]
Thanks @danmarsden 

I've created the PR for whenever you have a chance to review please.
