### ISSUE TITLE
Automatic and unwanted sent of drafts

### ISSUE THREAD

**Issue by mariainserver** [danmarsden/moodle-mod_dialogue#66]
Good Morning.

First thank you for your contribution with this plugin. Although, I wanted to report an error found in the functionality. It could be reproduced by following the next steps: 

- Create conversation with 'Bulk open rule' by selecting 'All participants' and save as draft. 
- Enroll one or more users.
- The draft **automatically is sent** to all students.

This error occurs in Moodle 3.4 with Dialogue (2017111300).

Thank you

**Comment by troywilliams** [comment]
Thanks for reporting the issue.

Troy

**Comment by danmarsden** [comment]
I haven't been able to reproduce this - flagging as closed, but let me know if you find this issue with a more recent version of moodle and the latest dialogue code.
