### ISSUE TITLE
mod_dialogue causing course backup/restore to fail on Totara 12

### ISSUE THREAD

**Issue by logan-reynolds** [danmarsden/moodle-mod_dialogue#67]
When attempting to backup and restore a course containing an instance of mod_dialogue latest version 2017051500 for M33 (which Totara 12 is based on), course restore fails at 63% with the following fatal error writing to the database.  My apologies that this is all of the error I could retrieve, as it was not printed to the UI and was truncated in webserver logs:
```
Got error 'PHP message: loading controller from db
PHP message: Default exception handler: Error writing to database Debug: Column 'maxattachments' cannot be null
INSERT INTO mdl_dialogue ("course","name","intro","introformat","maxattachments","maxbytes","usecoursegroups","notifications","notificationcontent","multipleconversations","timemodified") VALUES(?,?,?,?,?,?,?,?,?,?,?)
[array (
  0 => 5,
  1 => 'testdialoge',
  2 => '',
  3 => '1',
  4 => NULL,
  5 => NULL,
  6 => '0',
  7 => '1',
  8 => '0',
  9 => '0',
  10 => '1551916619',
)]
Error code: dmlwriteexception
* line 520 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 1262 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1308 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
* line 79 of /mod/dialogue/backup/moodle2/restore_dialogue_stepslib.php: call to mysqli_native_moodle_database->insert_record()
* line 137 of /backup/util/plan/restore_structure_step.class.php: call to restore_di...'
```
I haven't tried on Moodle versions to see if this bug occurs there also but my assumption is that it will, since it's caused by data being stored in the plugin's own tables (i.e. this wouldn't change whether running Moodle or Totara.)  This is considered a serious error, because it makes the administrator unable to make restored copies of any course containing an instance of the plugin.

**Comment by danmarsden** [comment]
Hi @logan-reynolds - I've just had a look at the code and I can see maxattachments comes from the site level setting - not the backup - it has a default value of 5 and is probably not set in your Totara site - If you are still having issues you should visit the site level dialogue settings page and make sure it has a value set.
Closing this for now, but please feel free to create a new issue if you can identify further information.

thanks,
