### ISSUE TITLE
mod_dialogue: Unable to select more than one student when creating a new message in a Dialogue

### ISSUE THREAD

**Issue by kiratskitizing** [danmarsden/moodle-mod_dialogue#75]
**Environment:**
Moodle - 3.9.3+ (Build: 20201113)
Dialogue - 2017111300

**Replication:**
1. Create a course and enrol three student users.
2. Turn editing on.
3. Add a Dialogue activity.
4. Go to the Dialogue activity.
5. Click the "Create" button.
6. In the Open with / People field, type the student user's name and select it.
7. The selected student will be added onto the field.
8. Repeat step 6 and use a different student's name,

**Result:**
Notice that the auto search while typing does not work. You will not be able to select multiple students.

**Comment by nigelbirch** [comment]
Can confirm we have exactly the same issue.

Worked until 10th of November and stopped overnight.

Moodle - 3.9.3+ (Build: 20201113)
Dialogue Version: 2017111300

It seems to replicated on all versions of moodle we have, even our local version.

**Comment by troywilliams** [comment]
I have done any work on the plugin for a long time. Last commit on master April 2019
https://github.com/troywilliams/moodle-mod_dialogue/commit/d97f486967b6657c6c045eb0562875958d619a17

You can only add one student per dialogue, You have never been able to select multiple students from the autoselect drop-down.

Please put in a feature request, it is unlikely I will get to this anytime soon.

Kind regards

**Comment by danmarsden** [comment]
latest version now users the core autocomplete form component so this should appear more like other core Moodle forms now.
