### ISSUE TITLE
Evaluate plugins broken-ness under v3.9.x LTS

### ISSUE THREAD

**Issue by troywilliams** [danmarsden/moodle-mod_dialogue#78]
Evaluate plugins broken-ness under v3.9.x LTS

- [ ] Missing callbacks https://docs.moodle.org/dev/Callbacks

**Comment by RaimundE** [comment]
Hi Troy,
happy to hear that you're taking development up again - we'll keep an eye on this thread!
Raimund

**Comment by danmarsden** [comment]
closing this one - it seems to work in 3.9 and there aren't any specfic issues mentioned in this issue.
